# Generated by Django 5.0.6 on 2024-06-30 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("created_time", models.DateField(auto_now_add=True)),
                ("last_visited", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Connections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=4000)),
                ("created_time", models.DateField(auto_now_add=True)),
                (
                    "unique_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_id",
                        to="ChatApi.device",
                    ),
                ),
            ],
        ),
    ]
