# Generated by Django 5.0.6 on 2024-07-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ChatApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcode",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
