# Generated by Django 5.0.6 on 2024-07-06 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ChatApi",
            "0002_remove_connections_text_remove_connections_unique_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Connections",
            new_name="RoomCode",
        ),
    ]
