# Generated by Django 5.0.6 on 2024-07-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ChatApi", "0002_roomcode_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomcode",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
