# Generated by Django 5.0.6 on 2024-07-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ChatApi", "0003_rename_connections_roomcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_visited",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="messages",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="roomcode",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
