# Generated by Django 5.0.6 on 2024-07-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ChatApi", "0005_device_room_delete_deviceinroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomcode",
            name="CT_code",
            field=models.IntegerField(unique=True),
        ),
    ]
